name: Build Docker Image

on:
  push:
    branches: [ "release/prep", "dev/test" ]
  pull_request:
    branches: [ "release/final" ]
    types: [ closed ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get version from README
      id: version
      run: |
        VERSION=$(grep -oP 'Version \K\S+' README.md)
        echo "::set-output name=version::${VERSION}"
    - name: Set Image Tag
      run: |
        if [[ "${{ github.ref }}" == refs/heads/release/final ]]; then
          TAG=${{ steps.version.outputs.version }}
        else
          DATE=$(date +%Y%m%d)
          TAG=${{ steps.version.outputs.version }}-$DATE
        fi
        echo "Building image with tag $TAG"
    - name: Build Docker Image
      run:
        docker build . --file Dockerfile --tag strk1204/stt:$TAG
    - name: Push to Docker Hub
      if: github.ref == 'refs/heads/release/final' || github.ref == 'refs/heads/release/prep' || github.ref == 'refs/heads/dev/test'
      run: |
        echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
        docker push strk1204/stt:$TAG
