name: Build Docker Image

on:
  push:
    branches: [ "release/prep", "dev/test" ]
  pull_request:
    branches: [ "release/final" ]
    types: [ closed ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get version from README
      id: version
      run: |
        VERSION=$(grep -oP 'Version \K\S+' README.md)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
    - name: Set Image Tag
      run: |
        if [[ "${{ github.ref }}" == refs/heads/release/final ]]; then
          TAG=$VERSION
        else
          DATE=$(date +%Y%m%d)
          TAG=$VERSION-$DATE
        fi
        echo "Building image with tag $TAG"
        echo "TAG=$TAG" >> $GITHUB_ENV
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build and push Docker image
      if: github.ref == 'refs/heads/release/final' || github.ref == 'refs/heads/release/prep' || github.ref == 'refs/heads/dev/test'
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          strk1204/stt:${{ env.TAG }}
          ${{ github.ref == 'refs/heads/release/final' && format('strk1204/stt:latest') || '' }}